# CREATE DATABASE nullbot;
# USE nullbot;

DROP TABLE IF EXISTS `file`;

CREATE TABLE `file`(
    id INT PRIMARY KEY AUTO_INCREMENT,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    directory VARCHAR(255) NOT NULL,
    is_dir BOOLEAN NOT NULL DEFAULT FALSE,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    owner_id BIGINT,
    owner_name VARCHAR(255),
    last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
