# CREATE DATABASE NullBot;
# USE NullBot;

DROP TABLE IF EXISTS `file`;

CREATE TABLE `file`
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
#     owner_id BIGINT NOT NULL,
#     owner_name VARCHAR(255) NOT NULL,
#     last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    directory VARCHAR(255) NOT NULL,
    is_dir INT DEFAULT 0 NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE
);
