# CREATE DATABASE NullBot;
# USE NullBot;

DROP TABLE IF EXISTS saying;

CREATE TABLE saying (
    id INT PRIMARY KEY AUTO_INCREMENT,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id LONG NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    text VARCHAR(1000) NOT NULL
);